# Generated by Django 3.0.8 on 2020-08-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
