# Generated by Django 3.0.8 on 2020-08-12 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0002_auto_20200812_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
