# Generated by Django 3.0.8 on 2020-08-15 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0003_auto_20200812_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeedsRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=200)),
                ('trust_deed_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200)),
                ('nominal_value_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_units', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Deeds Register',
            },
        ),
        migrations.AlterField(
            model_name='registerhistory',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
