# Generated by Django 3.0.8 on 2020-08-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0004_auto_20200815_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Account Manager'},
        ),
        migrations.RenameField(
            model_name='deedsregister',
            old_name='address',
            new_name='location',
        ),
    ]
