# Generated by Django 3.0.8 on 2020-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0005_auto_20200815_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedsregister',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='registerhistory',
            name='location',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
