# Generated by Django 3.0.8 on 2020-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0006_auto_20200815_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedsregister',
            name='location',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='registerhistory',
            name='location',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
