# Generated by Django 3.0.8 on 2020-08-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0007_auto_20200815_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
